### ISSUE TITLE
NFC interrupt as wakeup source

### ISSUE THREAD

**Issue by prattom** [NXPNFCLinux/nxp-pn5xx#14]
Hi is it possible to configure same NFC interrupt gpio as linux wakeup source? For ex. example I am using gpio <1 30>  ar irq gpio for NFC and thus whenever tag is detected interrupt is generated on this gpio. I want to use gpio as linuc wakeup source from sleep. When I run nfcDemoApp while it's waiting for tag I go to sleep and when tag comes interrupt is generated on gpio <1 30> and it also wakes up my board and then nfcDemoApp reads tag content.

**Comment by jgeslin** [comment]
Issue already addressed [here](https://github.com/NXPNFCLinux/linux_libnfc-nci/issues/44).
