### ISSUE TITLE
Example device tree overlay

### ISSUE THREAD

**Issue by kroegerama** [NXPNFCLinux/nxp-pn5xx#17]
Can you please provide an example device tree **overlay** (for the Raspberry Pi)?

I managed to compile the driver as standalone module, but it does not register the device /dev/pn544 after 'insmod pn5xx_i2c.ko', so I think my dts is wrong:

```
/dts-v1/;
/plugin/;

/ {
        compatible = "brcm,bcm2708";

        fragment@0 {
                target = <&i2c>;
                __overlay__ {
                        compatible = "nxp,pn547";
                        status = "okay";
                        reg = <0x28>;
                        clock-frequency = <400000>;
                        interrupt-gpios = <&gpio 23 0>;
                        enable-gpios = <&gpio 24 0>;
                };
        };
};
```

I compiled it using 'make dtbs' and got a dtbo file. Then I copied it to /boot/overlays and added 'dtoverlay=pn5xx' to /boot/config.txt.

**Comment by jgeslin** [comment]
To my mind your DTS declaration looks fine. 
However, the Raspberry Pi kernel you use may not support device tree. See https://www.raspberrypi.org/documentation/configuration/device-tree.md PART 4.
