### ISSUE TITLE
Stack not working on kernel 4.1.17+

### ISSUE THREAD

**Issue by mihaipop11** [NXPNFCLinux/nxp-pn5xx#5]
pn544 node in /dev fails to be added on newer kernels, tested on 4.1.17+ with raspberry pi b plus
also using the nxp demo image the nfc works but after apt-get upgrade, again the same problem, the pn544 node is not created in /dev. Is there a workaround for this issue?

**Comment by jgeslin** [comment]
pn544 node is not part of the linux kernel delivery (neither the RPi derived one). It must be added manually as described in Chapter 3 of related documentation [here](https://github.com/NXPNFCLinux/linux_libnfc-nci/blob/master/doc/AN11697%20-%20PN7120%20Linux%20Software%20Stack%20Integration%20Guidelines.pdf).
Command "apt-get upgrade" lead to update of the kernel of the board and as such the new installed kernel doesn't include nxp-pn5xx module.

**Comment by jgeslin** [comment]
Can we consider this item closed ?
